#!/usr/bin/env python2.7
import subprocess
import sys
import unittest
from urllib2 import urlopen


def git(*args):
    p = subprocess.Popen(['git'] + list(args), stdout=subprocess.PIPE)
    return p.stdout.read().decode('utf-8').strip()


def read_config():
    raw = git('config', '--list', '--null')
    pairs = [p.strip() for p in raw.split('\0') if len(p.strip())]
    return { k.lower(): v for k, v in [s.split('\n') for s in pairs] }

config = read_config()


rev_fields = [
    ('%H', 'sha'),
    ('%P', 'parents'),
    ('%D', 'ref'),
    ('%cN', 'committer.name'),
    ('%cE', 'committer.email'),
    ('%cI', 'committer.date'),
    ('%aN', 'author.name'),
    ('%aE', 'author.email'),
    ('%aI', 'author.date'),
]

rev_format = '%x00'.join([p for p, _ in rev_fields])


def dot_set(d, path, v):
    """Sets a key in a nested dict, where path is a string like 'foo.bar'"""
    key = path.split('.')
    for k in key[:-1]:
        d = d.setdefault(k, {})
    d[key[-1]] = v


def parse_commit(revline):
    commit = {}
    for field, value in zip([f for _, f in rev_fields], revline.split('\0')):
        dot_set(commit, field, value)

    commit['parents'] = [{ 'sha': s } for s in commit['parents'].split(' ')]
    return commit


def update_data(before, after, ref):
    revs = git('rev-list', '--pretty=%s' % rev_format, '--reverse',
               '%s..%s' % (before, after))

    commits = []
    for l in revs.splitlines():
        # skip header rows
        if l.startswith('commit '):
            continue

        commits.append(parse_commit(l))

    return {
        'ref': ref,
        'before': before,
        'after': after,
        'commits': commits
    }


def update(before, after, ref):
    print update_data(before, after, ref)


def assert_mock_lib():
    # avoid taking a dependency on mock for the normal operation of
    # the script.
    try: import mock
    except ImportError:
        print 'Install mock to run tests (`pip install mock`)'
        sys.exit(1)


def main():
    if sys.argv[1:] == ['--test']:
        assert_mock_lib()
        sys.argv = [sys.argv[0]] + ['--verbose']
        unittest.main()
        return

    for l in sys.stdin.xreadlines():
        before, after, ref = l.split()
        update(before, after, ref)


# Tests -- to run, use ./post-receive --test

class ConfigTest(unittest.TestCase):
    def test_works(self):
        conf = '\0'.join([
            'key1\nvalue1',
            'key2\nvalue2',
            'KEY3\nvalue3',
        ])

        from mock import patch
        with patch('__main__.git', return_value=conf):
            c = read_config()
            self.assertEquals(c['key1'], 'value1')

    def test_lowercases(self):
        conf = '\0'.join([
            'key1\nvalue1',
            'key2\nvalue2',
            'KEY3\nvalue3',
        ])

        from mock import patch
        with patch('__main__.git', return_value=conf):
            c = read_config()
            self.assertEquals(c['key3'], 'value3')

class UpdateDataTest(unittest.TestCase):
    def test_works(self):
        fields = [
            'sha', 'parentsha', 'ref', 'cname', 'cemail', 'cdate',
            'aname', 'aemail', 'adate',
        ]
        revs = '\n'.join([
            'commit sha',
            '\0'.join(fields),
            'commit sha',
            '\0'.join(fields),
        ])
        commit = {
            'sha': 'sha',
            'parents': [{'sha': 'parentsha'}],
            'ref': 'ref',
            'committer': {'name': 'cname', 'email': 'cemail', 'date': 'cdate',},
            'author': {'name': 'aname', 'email': 'aemail', 'date': 'adate',},
        }
        from mock import patch
        with patch('__main__.git', return_value=revs):
            self.assertEquals({
                'before': 'beforesha',
                'after': 'aftersha',
                'ref': 'refs/heads/master',
                'commits': [commit, commit]
            }, update_data('beforesha', 'aftersha', 'refs/heads/master'))


class ParseCommitTest(unittest.TestCase):
    def test_works(self):
        fields = [
            'sha', 'parentsha', 'ref', 'cname', 'cemail', 'cdate',
            'aname', 'aemail', 'adate',
        ]
        self.assertEquals(parse_commit('\0'.join(fields)), {
            'sha': 'sha',
            'parents': [{'sha': 'parentsha'}],
            'ref': 'ref',
            'committer': {'name': 'cname', 'email': 'cemail', 'date': 'cdate',},
            'author': {'name': 'aname', 'email': 'aemail', 'date': 'adate',},
        })

    def test_multiple_parents(self):
        fields = [
            'sha', 'parentsha1 parentsha2', 'ref', 'cname', 'cemail', 'cdate',
            'aname', 'aemail', 'adate',
        ]
        c = parse_commit('\0'.join(fields))
        self.assertEquals([{'sha': 'parentsha1'}, {'sha': 'parentsha2'}],
                          c['parents'])


class DotSetTest(unittest.TestCase):
    def test_one_key(self):
        c = {}
        dot_set(c, 'foo', 1)
        self.assertEquals(c, {'foo': 1})

    def test_nested(self):
        c = {}
        dot_set(c, 'foo.bar', 1)
        self.assertEquals(c, {'foo': {'bar': 1}})

    def test_merge(self):
        c = {'foo': {'bar': 1}}
        dot_set(c, 'foo.baz', 3)
        self.assertEquals(c, {'foo': {'bar': 1, 'baz': 3}})


if __name__ == '__main__':
    main()
